default:
  image: node:20
  before_script:
    - npm install
  cache:
    paths:
      - node_modules/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

deploy-pages:
  stage: deploy
  script:
    - npx quartz build
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
